### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by junmaqiang** [yannickcr/eslint-plugin-react#1172]
![wx20170506-093649](https://cloud.githubusercontent.com/assets/1819457/25768880/8dab6c3c-323f-11e7-8c3d-abb2c1638f6d.png)

**Comment by ljharb** [comment]
Hi! Please share text, not screenshots of text, so we can help you best.

Your screenshot has 4 errors; 2 of them will be resolved if you add `dispatch: PropTypes.func` to your propTypes.

The array error is because the rule wants you to use `arrayOf`, and be explicit about the contents of the array, as well.

**Comment by christiancho** [comment]
This is not Stack Overflow. If you're having issues with the core code of ESLint, this is the place to do. This is not the place for you to ask for help with your specific application.

**Comment by ljharb** [comment]
I would prefer people default to filing issues first; defaulting to stack overflow is the best way to make sure the core devs can't instantly tell you the solution to your common problem.
