### ISSUE TITLE
Configure to ignore certain directory for require-default-props rule

### ISSUE THREAD

**Issue by otakustay** [yannickcr/eslint-plugin-react#1224]
We are currently reviewing many of our react code and find `require-default-props` rule really useful, however there is a common exception:

If a component is designed to be connected to redux store, it's prop default value would be generated by reducers so we don't have duplicated declaration in `defaultProps`, also some of these props are not required, e.g. a `errorMessage` field will be produced by an ajax call

Also we find when comply with a common redux project structure, most connected components reside in a `container(s)` directory, so if we can configure `require-default-props` rule to ignore these certain directories could be nice

**Comment by ljharb** [comment]
You can put a `.eslintrc` file in that directory with whatever overrides you want.

However, it's still a better idea to explicitly specify the defaultProps, even if a reducer provides it - because if it *always* provides it, make it required; and if it doesn't, then you need a defaultProp for when it doesn't.

**Comment by otakustay** [comment]
Thanks for this hint, not arware that `.eslintrc` can reside in sub folders
