### ISSUE TITLE
react/jsx-sort-props not working

### ISSUE THREAD

**Issue by tobyf93** [yannickcr/eslint-plugin-react#1320]
I seem to be having trouble getting this rule to work.  The documentation references the following interface:
```
"react/jsx-sort-props": [<enabled>, {
  "callbacksLast": <boolean>,
  "shorthandFirst": <boolean>,
  "shorthandLast": <boolean>,
  "ignoreCase": <boolean>,
  "noSortAlphabetically": <boolean>,
  "reservedFirst": <boolean>|<array<string>>,
}]
```

My current configuration is `"react/jsx-sort-props": [2]`.  I have omitted the options which seem to work fine for other rules in the library.  Don't get any errors for the following component:
```
<Component c="c" b="b" a="a" />
```

**Comment by ljharb** [comment]
There must be something else going on - the test cases (https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-sort-props.js#L106, https://github.com/yannickcr/eslint-plugin-react/blob/master/tests/lib/rules/jsx-sort-props.js#L162) seem pretty solid.

Can you provide a full repro case, not just with options omitted?

**Comment by tobyf93** [comment]
https://github.com/tobyf93/jsx-sort-props-issue

`npm run lint` will give you an error about boolean attributes but not prop order...

**Comment by tobyf93** [comment]
same result for:
```
"react/jsx-sort-props": [2, {
  "callbacksLast": true,
  "shorthandFirst": true,
  "shorthandLast": true,
  "ignoreCase": true,
  "noSortAlphabetically": true,
  "reservedFirst": true
}]
```

**Comment by tagoro9** [comment]
I just run into this issue too. I think that when `reservedFirst` is enabled and `noSortAlphabetically` is off, then the alphabetical order is only enforced within the reserved props.

Adding a test case like this shows the issue:

```JS
{
  code: '<App key={2} b a />',
  options: reservedFirstAsBooleanArgs,
  errors: [expectedError]
}
```

I don't know if the expected behavior is that sorting is only enforced within the reserved props, but I would expect the alphabetical order to also be enforced in the other props.

I think I have a fix for this, so I'm gonna submit a PR with it. If this fix is not desired and current behavior is the desired, I apologize for all this noise.

**Comment by sadarshannaiynar** [comment]
Still not working ay working fix?
