### ISSUE TITLE
[no-array-index-key] throw error when id used along with item attribute

### ISSUE THREAD

**Issue by hozefaj** [yannickcr/eslint-plugin-react#1436]
When `idx` is used in conjunction with some `item` thats passed into array, the rule throws an error.

```js
this.props.items.map((item, idx) => {
  <div key={item.name + idx}> // Do not use Array index in keys  react/no-array-index-key
    // doing stuff
  </div>
}
```

In this case, `idx` is used with the name which will guarantees uniqueness here even if `name` is not unique by itself.

**Comment by jseminck** [comment]
The issue isn't really related to uniqueness. Using only the index is also unique.

Let's say you have two items in your array generating these keys :

```
firstName-0
secondName-1
```

When your array is re-ordered, it will generate these keys:

```
secondName-0
firstName-1
```

The keys have changed, and React won't be able to apply it's optimisations related to array ordering since the keys have changed.

If your keys simply were `firstName` and `secondName` then React can figure out the two elements were swapped.

**Comment by hozefaj** [comment]
@jseminck Yes you are right. I guess in my use case, there will not be reordering, but rather name is not unique. But there are others ways to generate keys as well.

The articles are useful. Closing the issue.
