### ISSUE TITLE
"no-window-in-render" rule?

### ISSUE THREAD

**Issue by magicmark** [yannickcr/eslint-plugin-react#1456]
@yannickcr @ljharb is there a rule to enforce "no globals in render method" etc? Would this be a good rule?

Motivation: this helps to enforce SSR renderable components.

(Assuming you want SSR, is there ever a good reason to access `window` or global vars in `render()` (or any prior lifecycle method)?)

I also wonder how hard this would be to lint 🤔

Thanks!

**Comment by ljharb** [comment]
Globals are fine; the only place `window`, `document`, or any other browser-specific feature should be used is in `componentDidMount` or event handlers.

I think it'd be exceedingly hard to lint for.

**Comment by magicmark** [comment]
> Globals are fine

Unless it's a fresh VM per request, this could lead to different markup on subsequent requests though right? (hence the motivation to want to lint against this)

**Comment by ljharb** [comment]
Reading globals is fine if nothing writes to them. Obviously yes, you have to have a fresh VM per request, but that's always true due to stateful modules unrelated to globals.

If you can catch some things perfectly, then it's maybe ok to not catch all things, but we don't want false positives. It's really hard to have a general guidance here; it's often case by case.
