### ISSUE TITLE
Add a rule to enforce extending React.PureComponent instead of React.Component?

### ISSUE THREAD

**Issue by Gaafar** [yannickcr/eslint-plugin-react#1667]
Would it make sense to add a rule to enforce components to be pure i.e: `extend React.PureComponent`

This would be very useful in redux projects where you want to enforce all components to rely on shallow prop comparison.

**Comment by ljharb** [comment]
I'm unclear why you'd ever want to force all components to do that; PureComponent is a blunt instrument that blocks the entire subtree from updating, including in response to context changes. There's rarely a codebase where every component in the app can be pure and also correct.

I'd be concerned about how often a rule like this would have to be overridden.

**Comment by Gaafar** [comment]
We're working in a relatively large team and I want everyone to use PureComponent by default to avoid a lot of unneeded rendering. If a component is not pure in that sense (which we're trying to avoid), I want to make it explicit by adding a comment to disable this rule. Does this seem like a valid use case?

**Comment by ljharb** [comment]
Airbnb has learned the hard way that overusing PureComponent actually hurts performance. Using PureComponent is a *bad* idea unless the component typically renders more than once with the same referentially equal props, because the shouldComponentUpdate logic incurs a cost.

I’d urge you to reconsider indiscriminately applying a very fine-trained optimization technique as the default.

**Comment by hedgepigdaniel** [comment]
Do you have a link to support the finding that PureComponents hurt performance?

I haven't tested, but it makes sense to me that PureComponents would provide a large performance boost by removing the need to rerender entire trees of components (other than potentially a single node somewhere that has changed. A shallow object comparison should not take significant time, and it can skip rendering for the entire tree of components inside.

**Comment by ljharb** [comment]
@hedgepigdaniel not a link, just airbnb’s anecdotal experience.

**Comment by foray1010** [comment]
I doubt that PureComponent hurt performance as it is just shallow compare of props and state (https://github.com/facebook/react/blob/4fe6eec15bc69737910e5c6c749ebc6187d67be0/packages/react-reconciler/src/ReactFiberClassComponent.js#L259-L263). There are much more costly codes in js.

As a code reviewer/programmer, I prefer to reduce time on deciding where to use PureComponent to optimize things, it should be fine to use it as default

**Comment by ljharb** [comment]
@foray1010 in fact it does, because the comparison itself is slow. Renders can happen thousands of times in a minute.

It's totally fine to selectively use, or not use, a PureComponent - which is why a naive rule such as this wouldn't serve anyone.

I'm going to close this unless other collaborators have a different opinion.

**Comment by alexmnv** [comment]
> This would be very useful in redux projects

Actually, it's the other way around. Because the HOC produced by `connect()` with default options already impelements `shouldComponentUpdate` logic with shallow state props comparison. See [docs](https://react-redux.js.org/api/connect#pure-boolean). So making the wrapped component extend PureComponent will have no effect other than double props comparison.

**Comment by shakhbulatgaz** [comment]
Can't we inplement a lighter version of the suggested rule? 
I mean, at least advice to use `PureComponent`, if no `props.children` is found.
