### ISSUE TITLE
Can't normal recognize using flow props in static methods

### ISSUE THREAD

**Issue by OverVlad** [yannickcr/eslint-plugin-react#1777]
Get error from `[eslint] 'navigation' PropType is defined but prop is never used (react/no-unused-prop-types)` when declaring prop types via flow in static methods, but I used this variable in static method code.

```
import type { NavigationScreenProp } from 'react-navigation';

export default class ComponentName extends Component<{}> {
  static navigationOptions = ({ navigation }: { navigation: NavigationScreenProp }) => ({ // error here
    headerLeft: (<NavigationBtn onPress={() => navigation.goBack()} />),
})
//... other code here
}
```

Have this plugins in .eslintrc `"plugins": ["react", "react-native", "flowtype", "flow"],`

**Comment by ljharb** [comment]
In this case, that's just the type of whatever's passed into `navigationOptions` - that provides no guarantee that `this.props.navigation` is used.

The real issue is that you're passing the entire props object around, which is both an antipattern and impossible to lint properly. If you extract `navigation` prior to calling `navigationOptions`, you won't run into trouble.

**Comment by OverVlad** [comment]
@ljharb But this method (navigationOptions) created by `react-navigation` and i can't control what it passed to this method

**Comment by ljharb** [comment]
How does react-navigation get your props object in the first place?

**Comment by OverVlad** [comment]
@ljharb I understand that is it no-props, but when you use flow it's necessary to declare entry function types.

https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e

**Comment by OverVlad** [comment]
How can I use destructuring function params in Component methods if flow requires declaring types for each parameter?

**Comment by OverVlad** [comment]
I see that this problem only with external libs

**Comment by ljharb** [comment]
I understand you want to declare flow types on the function arguments.

However, the `no-unused-prop-types` rule doesn't care about random function argument types, it only cares about component props.

Component methods don't get props - they get arguments. The only thing in a class-based component that's "props" is `this.props`, and anything you need out of it should be explicitly destructured instead of passed into a function.

In other words, here's your props:
 - SocialTradersCarousel's data: https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-first-js-L59
 - PortfolioScreen's navigation: https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-second-js-L90 and https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-second-js-L93 and https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-second-js-L118.

Now that's established, I do see that the flow type is specifying what the props are - and that no-unused-prop-types is warning on them means that the plugin is picking that up.

Which of these two components is getting the warning? As I've said, https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-second-js-L41 is not a prop usage, so the use of the `NavigationScreenProp` flow type there is irrelevant. https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-second-js-L80-L96 is what should be counting `navigation` as used (that you should never use arrow functions in a class property, and only constructor-bound instance methods isn't the actual issue, but it's worth mentioning), as well as https://gist.github.com/OverVlad/a11d62a965798ea3030769dedda59f7e#file-second-js-L118 inside `render`.

What external libs are the issue in your gist?

**Comment by OverVlad** [comment]
@ljharb react-navigation and react-native-snap-carousel are occurs this error

**Comment by ljharb** [comment]
ahh i think i see the issue - you’re using render props, which are functions that return jsx, thus this plugin is considering them components.

**Comment by ljharb** [comment]
I'm going to assume that our component detection has improved to the point where this is no longer a problem. If that's incorrect, please file a new issue with a repro.
