### ISSUE TITLE
[fixed]no_console rule is ignored when using eslint-plugin-react

### ISSUE THREAD

**Issue by Doums** [yannickcr/eslint-plugin-react#1969]
Hi,

"eslint": "^5.5.0",
"eslint-plugin-react": "^7.11.1",

eslintrc.js
```
module.exports = {
  "env": {
    "browser": true,
    "es6": true
  },
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2018,
    "sourceType": "module"
  },
  "plugins": [
    "react"
  ],
  "rules": {
    "indent": [
      "error",
      2
    ],
    "linebreak-style": [
      "error",
      "unix"
    ],
    "quotes": [
      "error",
      "single"
    ],
    "semi": [
      "error",
      "never"
    ],
    "no_console": 0    // 0 = off
  }
};
```

With this config, when I use `console.log` in my code, it's highlighted 'Unexpected console statement'
If I remove both `"jsx": true` and `"plugin:react/recommended"` it's works but I lose the JSX support.

It's an issue.

**Comment by ljharb** [comment]
What is the code that it’s warning on? Are you sure you don’t have any other eslintrc files? You can see [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/index.js#L115) that the recommended config doesn’t touch that rule.

Perhaps the issue is that the rule is called “no-console”, not “no_console”?

**Comment by Doums** [comment]
Yes it was that "no-console" instead of "no_console"  xD

Thank you, resolved
