### ISSUE TITLE
New exception option for react/require-default-props rule

### ISSUE THREAD

**Issue by mgcrea** [yannickcr/eslint-plugin-react#1987]
Would be great if we could add an exclusion pattern for the check. A bit like the `exception` option for the [id-length](https://eslint.org/docs/rules/id-length) rule (ideally with wildcard support).

In my case, working on a react-native project, it would be nice not to have to set defaultProps for every optional styling props, they are everywhere on a react-native project (eg. `containerStyle`, `labelStyle`, `textStyle`, etc.) and adding `null` defaultProps to evey possible style option for short pure components is really verbose and really reduces readability in my opinion.

Thanks for considering this! Would happily work on a PR if there is consensus.

**Comment by ljharb** [comment]
I think that if it reduces readability to supply defaults for all the optional props your component has, that might be an indicator that your component has too many props :-/

**Comment by mgcrea** [comment]
The issue is more the "weight" of these non-informative nullable defaultProps vs. the actual length of the component. In fact the shorter the component, the more bothersome the noise is, as it takes proportionally a lot of visual space. For instance:  

```js
type Props = {
  items: Array<Object>,
  containerStyle?: ViewStyleProp,
  inputContainerStyle?: ViewStyleProp,
  leftIconContainerStyle?: ViewStyleProp,
  rightIconContainerStyle?: ViewStyleProp,
  required?: Boolean
};
export default class StyledInput extends PureComponent<Props> {
  static defaultProps = {
    required: false,
    containerStyle: null,
    inputContainerStyle: null,
    leftIconContainerStyle: null,
    rightIconContainerStyle: null,
  };

  render() {
    const {
      items,
      leftIcon,
      required,
      containerStyle,
      inputContainerStyle,
      leftIconContainerStyle,
      rightIconContainerStyle,
      ...otherProps
    } = this.props;
    if (leftIcon) {
      leftIcon.color = colors.grey3;
    }
    return (
      <Input
        autoCorrect={false}
        containerStyle={[styles.container, containerStyle]}
        inputContainerStyle={[styles.inputContainer, inputContainerStyle]}
        leftIconContainerStyle={[styles.leftIconContainer, leftIconContainerStyle]}
        rightIconContainerStyle={[styles.rightIconContainer, rightIconContainerStyle]}
        inputStyle={[styles.input]}
        leftIcon={leftIcon}
        rightIcon={required ? <RequiredIcon /> : null}
        {...otherProps}
      />
    );
  }
}
```

**Comment by ljharb** [comment]
To be honest I think that having 5 optional props is the issue; having 5 defaultProps for them increases the clarity lost from having the props be optional in the first place.

**Comment by job13er** [comment]
@mgcrea I was running into something similar, and doing a little digging w.r.t. `flow` and `defaultProps`, I'm not sure you want to use the `react/require-default-props` rule when using `flow`. 

According to [Flow docs](https://flow.org/en/docs/react/components/#toc-using-default-props) and the discussion in [this issue](https://github.com/facebook/flow/issues/1660), the proper typing for optional props with a default set in `defaultProps` is to *not* mark them as optional in the type definition for `Props`.  This seems to be because, within the contexts of the component, that property is no longer optional (it won't be `undefined`, unless, of course, that's what you set the default to). When someone uses your component, `flow` won't complain if they leave off a seemingly required property if it has an entry in `defaultProps`. If you do mark it as optional in the type definition, then `flow` will keep warning you that you need to guard agains it being `undefined`, even though it never will be, leading to the writing of unreachable code :( With a boolean, it's probably less likely you'll run into the unreachable code situation, unless you try to pass it into somewhere that's explicitly expecting a boolean, but for other types it happens more often. 

I also didn't like having to explicitly set defaults for optionals to `undefined` when, to me, the `flow` type at the top made that totally clear. One thing you may want to consider is what the `react/require-default-props` rule is gaining you if you're already using `flow`. I actually really want to know, because I'm considering just turning that rule off in my project, since I'm hitting a lot of unreachable code situations when trying to make both `flow` and that rule happy. If it really does provide something useful when combined with `flow`, I'd love to hear about it, as that might change my mind.

**Comment by mehdivk** [comment]
I've got another use case for an exclusion option of some sort.

Say, we got a `<Button />` component that supports an optional `className` prop. When provided with a value for the mentioned `className` prop, the component attaches the CSS class to the actual DOM element. 

You may say that well then set `''` as the default value and you should be good to go. Think of 200 components that all have the same prop and it suddenly becomes a tedious task. Same goes for events like `onClick`, `onChange`. 

I really like this rule as it eliminates to check the default props during code reviews but things like `className` don't need a default value. 

Thanks for the great work :)
