### ISSUE TITLE
Extend react/jsx-props-no-multi-spaces to catch extra line breaks.

### ISSUE THREAD

**Issue by jsphstls** [yannickcr/eslint-plugin-react#2223]
```javascript
<button
  title='Some button'

  type='button'
/>
```

I was unable to find a rule that would prevent this and I think `react/jsx-props-no-multi-spaces` would be the most relevant one to extend. The issue is not that people would really do this. Instead, the goal is to improve the autofixing benefits of an existing rule with a hopefully minor adjustment.

**Comment by ljharb** [comment]
That sounds reasonable - want to make a PR?

**Comment by iiison** [comment]
is some one working on this?

**Comment by ljharb** [comment]
nope, go for it.

**Comment by ljharb** [comment]
@iiison this issue is for adding additional warnings to the rule.

Separately, it would be ideal to maximize what can be safely autofixed.

**Comment by RisingGeek** [comment]
It's still not auto fixing extra line breaks
Versions that I'm using
eslint: 7.32.0
eslint-plugin-react: 7.28.0

Am I missing something?

**Comment by ljharb** [comment]
It isn’t supposed to; it just warns on them.

**Comment by roryabraham** [comment]
I actually am not a fan of this change, since it disallows comments over certain props in multiline jsx code. Leading to lots of ugly code like this:

```jsx
<MyComponent
    someProp
    
    // Some comment about a prop's usage
    // eslint-disable-next-line react/jsx-props-no-multi-spaces
    someOtherProp
/>
```

As opposed to this:

```jsx
<MyComponent
    someProp
    
    // Some comment about a prop's usage
    someOtherProp
/>
```

@jsphstls stated in his original posting:

> The issue is not that people would really do this. Instead, the goal is to improve the autofixing benefits of an existing rule with a hopefully minor adjustment.

But the PR that was merged actually doesn't introduce any autofixing benefits. In my opinion we should revert this change, or barring that allow the user to configure a maximum number of allowable line breaks in multiline components.

**Comment by roryabraham** [comment]
Actually though, this isn't really necessary since `no-multi-spaces` covers single-line JSX props. So this rule is really just helpful in disabling multiple newlines between props. It would still be nice to be able to set a maximum of `1` blank line between JSX props (allowing for comments on props but not multiple blank lines).

**Comment by ljharb** [comment]
@roryabraham that seems like a reasonable option to add, if you wanted to send a PR with lots of test cases.
