### ISSUE TITLE
Rule Proposal: Require "shouldComponentUpdate" or PureRenderMixin to be applied

### ISSUE THREAD

**Issue by EvNaverniouk** [yannickcr/eslint-plugin-react#240]
On our team, we want to ensure all components are optimized. This means either PureRenderMixin must be applied on the component, or the component must have a `shouldComponentUpdate` method defined. It would be great if ESLint could warn developers when they have forgotten to optimize.

**Comment by Daniel15** [comment]
Using `PureRenderMixin` on every single component can actually *reduce* performance, as it means *every* component in a tree needs to do a shallow comparison of props and state whenever a prop passed from the top level all the way down the tree does change. This can add many unneeded shallow equality checks.

The key to optimisation is to determine the minimal number of shallow comparisons you can add while still improving perf, rather than blindly adding `PureRenderMixin` to everything. Often this means only using `PureRenderMixin` on top-level containers and other "heavy" components, and avoiding it on lightweight components. :smile: 

Consider this contrived example:

```js
var HeavyA = React.createClass({
  mixins: [PureRenderMixin],
  _doSomeStuff() {
    this.setState({stuff: doHeavyCalculations()});
  },
  render() {
    return <HeavyB stuff={this.state.stuff} doStuff={this._doSomeStuff} />;
  },
});

var HeavyB = React.createClass({
  mixins: [PureRenderMixin],
  render() {
    var moreStuff = doMoreHeavyCalculations();
    return (
      <LightC 
        stuff={this.props.stuff} 
        moreStuff={moreStuff}
      />
    );
  },
});

var LightC = React.createClass({
  render() {
    return (
      <div>
        Hello from {this.props.stuff} and {this.props.moreStuff}!
      </div>
    )
  },
});
```

If `LightC` is only rendered within `HeavyB`, there's actually no advantage to adding `PureRenderMixin` to `LightC` and it only ever *reduces* performance. `HeavyB`'s usage of `PureRenderMixin` already handles not re-rendering `HeavyB` (and thus not re-rendering `LightC`) if the data doesn't change, so checking the props again in LightC is unnecessary.

**Comment by mxstbr** [comment]
Is this by chance being worked on? This would be a great addition that'd be much appreciated!

**Comment by EvNaverniouk** [comment]
I've taken a stab at this in the `eslint-plugin-cumul8` repo (`npm install eslint-plugin-cumul8`). Will test this in various codebases before submitting as a PR to `eslint-plugin-react` Looking to others for testing and feedback.

Documentation here: https://github.com/Eight-Solutions/eslint-plugin-cumul8/blob/master/docs/rules/react-require-optimization.md
