### ISSUE TITLE
feat: react/no-deprecated fixer

### ISSUE THREAD

**Issue by Hotell** [yannickcr/eslint-plugin-react#2456]
react/no-deprecated is awesome! What would be even better/more helpful is to implement fixer that renames those methods to `UNSAFE_*'

Thanks!

**Comment by ljharb** [comment]
That’s not a safe fix - primarily because packages that still support react < 16.3 need them.

**Comment by Hotell** [comment]
Ah right! Can't we determine which version of react is used and apply the fix if applicable ?

**Comment by ljharb** [comment]
That's a potential option, but while i think it's fine to change *warnings*/errors based on the react version, making the autofix dependent on that seems a lot riskier.

Since most of these warned methods should be changed to *new* lifecycle methods, and not just casually prefixed with "UNSAFE_", it almost seems like an autofix here would be worse.

**Comment by Hotell** [comment]
Right also I just realized that there is a codemod for that. https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#renaming-unsafe-lifecycle-methods
