### ISSUE TITLE
Missing lock file

### ISSUE THREAD

**Issue by friederbluemle** [yannickcr/eslint-plugin-react#2485]
This project does not have a dependency lock file, meaning that future builds are **unpredictable and might break at any time** (especially since most dependencies in `package.json` are declared as a version range). Even with fixed versions in `package.json`, a missing lock files means that there is no control over transitive dependency versions.

The `.gitignore` file in this repo [mentions](https://github.com/yannickcr/eslint-plugin-react/blob/master/.gitignore#L23):

> Only apps should have lockfiles

However, this is not true. Libraries, just like apps, should have a lock file. A great and detailed explanation is given at https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

Please add a lock file (preferably `yarn.lock`) to this repository.

**Comment by ljharb** [comment]
I wouldn’t say I’m missing it, bob.

Indeed, only apps should have lockfiles. That the build could break at any time is a *feature* - because that’s what consumers experience too.

Using a dev-only lockfile like package-lock or yarn.lock is hostile to consumers, since it’s putting the comfort of maintainers before that of users.

As long as i have a say in it, no published project I’m involved in will ever have a lockfile.
