### ISSUE TITLE
Not really understand the function of the variable 'hasBeenWritten' in usedPropTypes.js

### ISSUE THREAD

**Issue by Wangszzju** [yannickcr/eslint-plugin-react#2494]
In util/usedPropTypes,  we have a function named createPropVariables：
```javascript
function createPropVariables() {

  let propVariables = new Map();
  let hasBeenWritten = false;
  const stack = [{propVariables, hasBeenWritten}];

  return {
    pushScope() {
      // popVariables is not copied until first write.
      stack.push({propVariables, hasBeenWritten: false});
    },
    popScope() {
      stack.pop();
      propVariables = stack[stack.length - 1].propVariables;
      hasBeenWritten = stack[stack.length - 1].hasBeenWritten;
    },
    set(name, allNames) {
      if (!hasBeenWritten) {
        // copy on write
        propVariables = new Map(propVariables);
        Object.assign(stack[stack.length - 1], {propVariables, hasBeenWritten: true});
        stack[stack.length - 1].hasBeenWritten = true;
      }
      return propVariables.set(name, allNames);
    },
    get(name) {
      return propVariables.get(name);
    }
  };
}
```

Now we have a unit-test case like: 
```js
       class Hello extends React.Component {
          render() {
            const props = this.props;
            const trans = () => { const { test } = props };
            return <div>Hello World</div>;
          }
        }
```

When we enter the function `render`, we run the `set` method and the variable, `hasBeenWritten`, is false. It's reasonable because I think the variable points to the hasBeenWritten prop of the bottom element of the stack.

However, when we enter the function,`trans` we also run the `set` method, and the variable `hasBeenWritten`, is still false....Should it be equal to the hasBeenWritten prop of the second element of the stack （You know now, the second element is about the render function）？

It is really confusing for me that what the meaning of `hasBeenWritten` is.

**Comment by golopot** [comment]
The object `PropVariables` is used to record which variable points to which prop. In a simple implementation, when the linter enters a function declaration, the last stack is cloned and the clone is set as the current stack. In order to avoid unnecessary cloning, a technique called ["copy-on-write"](https://en.wikipedia.org/wiki/Copy-on-write) is applied, which postpone cloning until first write, since cloning is not necessary until the clone is modified. The value `hasBeenWritten` is part of the implementation of copy-on-write.
