### ISSUE TITLE
I wonder, is there any rule doesn't work with hook?

### ISSUE THREAD

**Issue by phakphumi** [yannickcr/eslint-plugin-react#2539]
For instance "react/no-access-state-in-setstate". Is this rule work correctly for react hooks
If it is not working. Is there any rules else that not work as well

**Comment by ljharb** [comment]
useState is not component state, despite its name, so that rule doesn’t and shouldn’t do anything for SFCs.

I’m sure a great number of rules don’t work for hooks, either because they haven’t been updated yet or because they don’t apply. Please file specific issues for each rule and code sample you want to work differently.

**Comment by qmcree** [comment]
I think @phakphumi's question is if there is an equivalent rule for `react/no-access-state-in-setstate` when using the `useState` hook. This would be a valid use case for a new rule (if there isn't one already), since it's still recommended to use the updater function syntax anytime you're setting state based on the previous state.

**Comment by ljharb** [comment]
There's no need for it, because it's perfectly fine to access the closed-over state result that `useState` provided in the hook - it's already intuitive and obvious that it's the old value. The reason for the rule is that it's not clear whether you intended to use the old or the new value (and worse, it's not guaranteed which one it will be).

**Comment by qmcree** [comment]
@ljharb Oh, then I must be misunderstanding the docs. If it's OK to use current state values when computing the _new_ state value _without_ an [updater function](https://reactjs.org/docs/hooks-reference.html#functional-updates), what is the value of using an updater function with `useState` then?

**Comment by ljharb** [comment]
ah, no, i guess i'm wrong about it. That suggests that indeed, a rule would be useful for the `useState` hook - but `eslint-plugin-react-hooks` seems like a better place for that to live.
