### ISSUE TITLE
Drop Node 8 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [yannickcr/eslint-plugin-react#2622]
Because it's [EOL](https://nodejs.org/en/about/releases).

It's probably a good idea to wait for ESLint 7, since that will drop Node 8.
https://github.com/eslint/eslint/releases/tag/v7.0.0-alpha.0
https://github.com/eslint/eslint/pull/12700

We can also drop support for older ESLint versions then, since we're doing a major release anyways.

**Comment by ljharb** [comment]
No, because EOL status is utterly irrelevant, and dropping support for EOL nodes makes it *harder* for those users to upgrade.

This package still supports eslint 3, and will do so for as close to *forever* as i can manage (i maintain 200+ packages that support down to node 0.4), and thus it will support all node versions eslint 3+ works on.
