### ISSUE TITLE
no-unescaped-entities: make fixable?

### ISSUE THREAD

**Issue by queengooborg** [yannickcr/eslint-plugin-react#2646]
It'd be nice if the `no-unescaped-entities` rule could be made fixable automatically.  Many times when I'm writing up something, I use normal apostrophes, and then go back to do the formatting.  However, it would be nice to have this plugin do it for me, picking the first suitable replacement.  I feel that since we're already smart about the linting, the fixing wouldn't be too far off.

**Comment by ljharb** [comment]
Normal apostrophes are typographically invalid in prose; they need to be `‘`/`’`. It would be very strange, I think, if the linter substituted straight quotes for the proper curly quotes.

Either way, the things this rule warns on are typically things that are ambiguous - they're just as likely to be mistakes (oops, i meant this text to be part of an element's tag) as to be intentional (i really meant to have jsx-looking stuff here, let's escape it!). I can't conceive of a safe heuristic for assuming one.

**Comment by MichaelFroelich** [comment]
Please at least fix the ones that are within HTML like code but are no where near those escape braces, ie:

div> This "here" can obvoiusly be fixed as it's between two divs  </div

**Comment by k-yle** [comment]
@ljharb would you accept a PR for this?

**Comment by ljharb** [comment]
@k-yle i'd be happy to review one, but I'm still not convinced there's any safe subset of these that can be autofixed.

**Comment by ljharb** [comment]
Closing, altho if someone provided a PR proving there's a safe way to autofix any of these, I'd always be happy to review it.
