### ISSUE TITLE
children/tag is missing in props validation

### ISSUE THREAD

**Issue by uriva** [yannickcr/eslint-plugin-react#2798]
I'm not sure what's happening here - I'm not using prop-types, just the eslint-plugin-react.

```javascript

import React from "react";

const RawHtml = ({ children = "", tag: Tag = "div", ...props }) => (
  <Tag {...props} dangerouslySetInnerHTML={{ __html: children }} />
);

export { RawHtml };

```

>  3:20  error  'children' is missing in props validation  react/prop-types
>  3:35  error  'tag' is missing in props validation       react/prop-types

**Comment by uriva** [comment]
I was missing
```
"rules": {
    "react/prop-types": 0,
}
```

**Comment by ljharb** [comment]
To be more accurate, you're missing:
```jsx
RawHTML.propTypes = {
  children: PropTypes.node,
  tag: PropTypes.oneOf(PropTypes.string, PropTypes.func),
  ...Tag.propTypes,
};
```

**Comment by uriva** [comment]
I mean, my opinion is that if you're going to annotate all your code, you might as well just use typescript :)

**Comment by JustFly1984** [comment]
Yeah, great advise!  I had to switch to typescript since the moment I’ve realised you can’t use prop types for null! And it is not considered to implementation, I guess cos uncle Bob... but since I’ve tamed typescript several years ago, no day to regret. Can’t go back to pure js anymore.

It takes several weeks to refactor big project to typescript for beginners, but after some learning curve it really shines and payback is awesome. You have no idea how many bugs you have until you type your project in strict mode.

**Comment by ljharb** [comment]
@uriva TypeScript is incapable of checking most of the things that PropTypes can.

@JustFly1984 check https://npmjs.com/airbnb-prop-types for `explicitNull`, it works fine.
