### ISSUE TITLE
react/jsx-pascal-case flags Styled.h1 as not being in pascal case

### ISSUE THREAD

**Issue by Kev-Y-Huang** [yannickcr/eslint-plugin-react#2914]
While using the Theme-UI [Styled Component](https://theme-ui.com/styled/) `<Styled.h1>` in gatsby, this plugin fires off a console warnings about not being pascal case
![image](https://user-images.githubusercontent.com/12895833/106489020-4f116c00-6482-11eb-8211-befbbb122133.png)

**Comment by ljharb** [comment]
the lint rule wants that to be `<Styled.H1>`, yes.

**Comment by Kev-Y-Huang** [comment]
Is there a reason then why when testing `<Styled.p>` does not raise the same errors? Is this intentional?

**Comment by Kev-Y-Huang** [comment]
I understand the reasoning behind the other error. Just trying to grasp the larger picture.

**Comment by ljharb** [comment]
"p" is one thing, where "h1" is two things ("h" and "1").

I can see the argument where if "p" is ignored, dot-anything should be ignored too. I suspect that this is more the rule overlooking the (rare, unidiomatic) use case of namespaced components, rather than an intentional decision.

The "ignore" option that will be included in the next release may help you here; perhaps also a separate option to control the behavior on namespaced tag names?

**Comment by Kev-Y-Huang** [comment]
Is it ok if I create a PR then for this feature?

**Comment by ljharb** [comment]
Sure. Let's first maybe discuss what the option would be named, and what its semantics would be :-)

**Comment by Kev-Y-Huang** [comment]
I guess most easily, the option could be named namespace and automatically set to false (?) where if set to true, it ignores all case issues after the dot. Perhaps that isn't rigorous enough in which case, do you have any suggestions as to what would be a better approach?

**Comment by Kev-Y-Huang** [comment]
Or perhaps the rule should not warn on components that start with a lowercase after the dot?

**Comment by Kev-Y-Huang** [comment]
Also, looking through the current logic, it seems that if the type is JSXNamespacedName or JSXMemberExpression, it does not verify at all the the string before the `.` or `:`.

For example, `<$Test.P>` or `<$Test:P>` are valid according to the rules.
