### ISSUE TITLE
Can a rule sentence-case be added that enforces text string sin Sentence case?

### ISSUE THREAD

**Issue by with-shrey** [yannickcr/eslint-plugin-react#2951]
I found this eslint plugin that works but it is not understanding react string literals(Example: `<div>Hi There</div>`)

https://www.npmjs.com/package/eslint-plugin-sentence-case

**Comment by ljharb** [comment]
It seems like it'd be relatively easy for that plugin to support JSX string literals as well, since that's not unique to react.

Additionally, sentence case both isn't trivial to enforce correctly, and would need to work for every language, so it's not a solution I think I'd want to sign up to maintain.
