### ISSUE TITLE
`master` is out of date

### ISSUE THREAD

**Issue by Enzime** [yannickcr/eslint-plugin-react#2970]
![21-04-20_10-45-31](https://user-images.githubusercontent.com/10492681/115320611-911a9600-a1c5-11eb-8a5a-0d2d5af2d316.png)

The latest commit in `master` according to both GitHub and `git` when I clone the repo is `495a4cf` from July 2020. This leads to GitHub displaying the latest release as `v7.21.5` from October 2020. However, I can see that the latest release on `npm` and from the tags is `v7.23.2`.

@ljharb

**Comment by ljharb** [comment]
The master branch is not remotely out of date. Github shows the commit authoring date, not the date the commit was landed. The latest commit - 495a4cf85e6e810802e9de1b5f6efe730cb485c7 - was landed in #2713 23 hours ago, which you can see by clicking on the commit sha, and then on the linked PR.

You're right about the github releases; altho the tags are up to date, i haven't manually created a github release since v7.21.5. I've just updated them.
