### ISSUE TITLE
7.27.0: error   'className' is missing in props validation  react/prop-types

### ISSUE THREAD

**Issue by brandonlenz** [yannickcr/eslint-plugin-react#3139]
In 7.27.0, an error began popping up that I didn't find anything specific for in the patch notes. Due to the behavior outlined in the example/comment linked below, this feels like an unintentional bug.

Example: https://github.com/trussworks/react-uswds/pull/1755#issuecomment-968995068

In short, this error is triggered by the inferred className props for react functional components, but not the children prop. Both of which I would expect to have similar behavior in terms of the need to explicitly define those props.

**Comment by ljharb** [comment]
This is quite intentional; every prop must be declared, but the decision was made a long time ago in this plugin to be more lax for "children" specially. I expect to tighten this up in the next major, if that ever happens.

I would, however, recommend always explicitly defining every propType, including `children`.

**Comment by brandonlenz** [comment]
Got it! Thanks for the explanation. I'll close this and update the PR I linked. Cheers!
