### ISSUE TITLE
[`jsx-sort-props`]: support multiline prop groups missing from npm package

### ISSUE THREAD

**Issue by renansigolo** [yannickcr/eslint-plugin-react#3201]
It looks like the version published on npm differs from the current documentation on the master branch, therefore the new functionality to support multiline prop groups which has already been merged to master it's not yet available when installing from npm. Cutting a new release should fix this issue.

[PR of the added feature](https://github.com/yannickcr/eslint-plugin-react/commit/f47deef684e5d5538776dd11be8b2e0724094e9a)

[Live Documentation on the master branch](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-sort-props.md#multiline)

<img width="1440" alt="Screen Shot 2022-02-12 at 12 12 03 am" src="https://user-images.githubusercontent.com/25624875/153597469-d1b72d73-7948-42e6-a99b-8c8439d1aaef.png">

<img width="1552" alt="Screen Shot 2022-02-12 at 12 02 10 am" src="https://user-images.githubusercontent.com/25624875/153597086-11fd837c-8d53-4bca-8dda-39a42e10e654.png">

<img width="1440" alt="Screen Shot 2022-02-12 at 12 01 13 am" src="https://user-images.githubusercontent.com/25624875/153597063-ca27d36f-980f-4666-a150-2d7271b12108.png">

**Comment by ljharb** [comment]
That's because in every repository on github since its inception, the master/default branch doesn't necessarily match what's published.

If you want to check the docs for a published version, look at its tag: https://github.com/yannickcr/eslint-plugin-react/tree/v7.28.0/docs/rules

and if you check the PR you linked, you can see that it's not present in any release tag.

Additionally, if you check the changelog on master, you can see it's in the "unreleased" section. https://github.com/yannickcr/eslint-plugin-react/blob/master/CHANGELOG.md#unreleased

A merged but unreleased change isn't an "issue" and can't be "fixed". When we're ready to cut a release, we will, and until then, all of this stuff is SUPPOSED to be unreleased.

**Comment by renansigolo** [comment]
Thanks for explaining me that and pointing me to the correct reference of the docs. I've wrongly assumed that the master branch would reflect the latest version on npm, and the changelog.md to be exactly the same as the GitHub Releases but it turns out that the "unreleased" section it's only shown in the changelog.md file and as release and deploy are different things I was trying to use a feature that has developed but not been made available on npm yet.

Sorry for raising an invalid issue, I'll make sure to look at the docs in the tag that corresponds to the correct version on npm from now on.
