### ISSUE TITLE
Whitelist for no-unknown-property rule?

### ISSUE THREAD

**Issue by insin** [yannickcr/eslint-plugin-react#351]
I have a [Babel plugin](https://github.com/insin/babel-plugin-react-html-attrs) which automatically converts `class` and `for` into `className` and `htmlFor`, and may expand to being configurable for other properties in the future - would it be possible to add a whitelist to no-unknown-property so people who use it don't have to disable this rule, since it's so useful for catching gotchas?

**Comment by yannickcr** [comment]
This can be useful, I'll try to find some time to do it (or don't hesitate to submit a PR if you want)

**Comment by JulianMayorga** [comment]
[You can ignore properties](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unknown-property.md#rule-options) like class and for by using the ignore property, so this issue seems solved.  Just add `"react/no-unknown-property": [2, { "ignore": ["class", "for"] }]` to your .eslintrc.json
