### ISSUE TITLE
babel-eslint vs eslint-plugin-babel vs eslint-plugin-react

### ISSUE THREAD

**Issue by ahmed1490** [yannickcr/eslint-plugin-react#446]
I am relatively still learning linting with eslint.

Can you please differentiate purpose of eslint-plugin-babel in comparison to babel-eslint vs eslint-plugin-babel ?

**Comment by yannickcr** [comment]
* [babel-eslint](https://github.com/babel/babel-eslint) is a parser, it will transform your JavaScript code into an [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) that will be used by ESLint to validate your code. You can see what an AST looks like on [AST Explorer](http://astexplorer.net). ESLint support [a few parsers](http://eslint.org/docs/user-guide/configuring#specifying-parser) with different capabilities. Babel-eslint is great since it does support all valid Babel code, so it is a good companion if you are already compiling your JavaScript with Babel.
* eslint-plugin-* are ESLint plugins, they add some additional rules to ESLint. Most of the plugins can be found on npm with the [`eslintplugin`](https://www.npmjs.com/browse/keyword/eslintplugin) keyword.
   * [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel) add some rules for some of the Babel experimental features which are not natively supported by ESLint because it is... experimental.
   * [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) add some rules specifically for [React](http://facebook.github.io/react), this mostly include good practices and JSX code formatting.

**Comment by ahmed1490** [comment]
Thank you very much! pretty clear :+1: :)

**Comment by ahmed1490** [comment]
should it be part of readme ?
