### ISSUE TITLE
Required props JSX validation

### ISSUE THREAD

**Issue by ccoffey** [yannickcr/eslint-plugin-react#530]
I would like a rule that looks for missing required props.

This should be an error
```javascript
<Text />
```

This should not be an error
```javascript
<Text name="cathal" />
```

Example component 

```javascript
const React = require('react');
const {Component, PropTypes} = React;

class Text extends Component {
  render() {
    return <div>Hello {this.props.name}</div>
  }
}

Text.propTypes = {
  name: PropTypes.string.isRequired
};

module.exports = Text;
```

**Comment by ljharb** [comment]
This is something that can be done at runtime, but at compile time would require parsing the module dependency graph, and evaluating the component module.

In other words, this is what PropTypes already do at runtime, and isn't likely to be something that is even *possible* to statically lint for.

In our tests, we override `console.warn` and `console.error` so that they throw, and voila, PropType warnings fail tests.

**Comment by yannickcr** [comment]
Like @ljharb said, when linting we only check files individually, so we are not aware of components definitions in other files. Because of that we can't know if its requirements are fulfilled.

You'll need to rely on PropTypes at runtime for that.
