### ISSUE TITLE
utils.isReturningJSX is returning false all the time

### ISSUE THREAD

**Issue by zachguo** [yannickcr/eslint-plugin-react#741]
I found this when I was working on a new rule. #736 

All following SFC nodes are considered not returning JSX by `utils.isReturningJSX(node)`. `utils.isReturningJSX(node.parent)` & `utils.isReturningJSX(node.body)` are both returning false too.

``` jsx
const Hello = (props, context) => {
  return <div>Hello {context.name}</div>;
};
```

``` jsx
const Hello = function(props, context) {
  return <div>Hello {context.name}</div>;
};
```

``` jsx
const Hello = (props, {name}) => {
  return <div>Hello {name}</div>;
};
```

**Comment by zachguo** [comment]
We may need a new util function like `isStatelessFunctionalComponent` to handle SFC detection. SFC detection has been discussed and requested many times: https://github.com/yannickcr/eslint-plugin-react/issues/512 https://github.com/yannickcr/eslint-plugin-react/issues/578 https://github.com/yannickcr/eslint-plugin-react/issues/672
And the util function should be unit tested.

**Comment by ljharb** [comment]
Certainly `isReturningJSX` should be fixed.

Separately, an `isSFC` function should be added, but that doesn't have to be done at the same time.

**Comment by mjackson** [comment]
As I suggested [here](https://github.com/yannickcr/eslint-plugin-react/issues/512#issuecomment-237386845) I believe the only way to create an accurate `isStatelessFunctionalComponent` method would be to check if a function is ever actually used as the first argument in `React.createElement`. Otherwise you're going to get a bunch of false positives with methods that return some JSX but aren't intended to be SFCs.

**Comment by ljharb** [comment]
We've done lots of improvements here, and I believe this original issue is fixed.

If there's further bugs, please open a new issue (or better, a PR with failing tests), and we'll address it.
