### ISSUE TITLE
Component exceptions for forbid-component-props?

### ISSUE THREAD

**Issue by clarabstract** [yannickcr/eslint-plugin-react#935]
Some components are are simple, slightly-extended stand-ins for standard html tags - e.g. a custom `<a>`-like component that is routing aware, or a custom `<img>` that knows how to look up images `src`s in a certain way. For such components, using `className` or `style` directly is perfectly fine (insofar as using them for standard html tags is too). Would be great if we could simply specify the exception list in the config object.

**Comment by janpaul123** [comment]
Alternatively, the `forbid-component-props` rule could be more like the `forbid-prop-types` rule, where we check it when defining prop types, instead of when instantiating a component. That way you can easily ignore the rule in legitimate cases, without having to ignore the the rule every single time you use the component.

**Comment by ljharb** [comment]
This can already be achieved with the current rule config options, by providing an object with `allowedFor`.
