### ISSUE TITLE
Rule proposal: no-useless-scu

### ISSUE THREAD

**Issue by nkt** [yannickcr/eslint-plugin-react#985]
`shouldComponentUpdate` method is useless when component extending `PureComponent`.

**Comment by ljharb** [comment]
It's worth noting that I think it will actually *work* - it just means there's no point in it extending PureComponent then. I'm 👍 on this rule.

**Comment by jseminck** [comment]
I'll take a look at this rule, since it was just recently requested again in https://github.com/yannickcr/eslint-plugin-react/issues/1217

It looks pretty easy to add:

* Validate the MethodDefinition name
* Validate that the method is declared in a PureComponent (for which a helper already exists)

Probably will need some help with the actual rule name and errors + docs. I suppose `no-useless-scu` is not a good name, as we want to warn the user not to extend `React.PureComponent` when they want to override `shouldComponentUpdate`?

**Comment by jseminck** [comment]
Nevermind. There is a PR already. Missed it.

**Comment by alexzherdev** [comment]
Fixed via #1084.
